export default {
  en: {
    email: 'E-mail',
    password: 'Password',
    login: 'Log In',
    facebookLogin: 'Log In with Facebook',
    goToSignIn: 'I don\'t have and account',
    goToLogIn: 'I already have an account',
    register: 'Register',
    name: 'Name',
    confirmPassword: 'Password Confirmation',
    city: 'City',
    invalidEmail: 'Invalid e-mail',
    wrongPassword: 'Invalid password',
    userNotFound: 'User not found',
    disabledUser: 'Blocked user\nPlease contact contact@trailspot.app',
    emailAlreadyInUse: 'E-mail already in use. Did you forgot your password?',
    authError: 'Auth error. Please try again later',
    forgotPassword: 'I forgot my password',
    writeYourEmail: 'Write down the email address of the account you want to recover',
    recoveryPasswordEmailSent: 'We have sent you a password recovery email. Access the link and change to your new password.',
    noCancel: 'No, cancel',
    yesSendEmail: 'Yes, please',
    wrongAuthMethod: 'This account already exists, but uses another form of login. You can trying to login with email or facebook.',
    ops: 'Oooooops!',
  },
  'pt-BR': {
    email: 'E-mail',
    password: 'Senha',
    login: 'Entrar',
    facebookLogin: 'Entrar com Facebook',
    goToSignIn: 'Eu não tenho uma conta',
    goToLogIn: 'Eu já tenho uma conta',
    register: 'Criar conta',
    name: 'Nome',
    confirmPassword: 'Confirme sua senha',
    city: 'Cidade',
    invalidEmail: 'E-mail inválido',
    wrongPassword: 'Senha incorreta',
    userNotFound: 'Usuário inexistente.',
    disabledUser: 'Usuário bloqueado.\nEnvie um e-mail para contact@trailspot.app',
    emailAlreadyInUse: 'E-mail já cadastrado em outra conta. Você esqueceu sua senha?',
    authError: 'Erro de autenticação. Tente novamente mais tarde',
    forgotPassword: 'Esqueci minha senha',
    writeYourEmail: 'Escreva abaixo o e-mail da conta que você deseja recuperar',
    recoveryPasswordEmailSent: 'Enviamos um e-mail de recuperação de senha para você. Acesse o link e altere para a sua nova senha.',
    noCancel: 'Não, cancelar',
    yesSendEmail: 'Sim, por favor',
    wrongAuthMethod: 'Esta conta já existe, mas utiliza outra forma de login. Você pode tentar fazer login com e-mail ou facebook.',
    ops: 'Ooops!',
  },
};
