export default {
  en: {
    email: 'E-mail',
    password: 'Password',
    login: 'Log In',
    facebookLogin: 'Log In with Facebook',
    goToSignIn: 'I don\'t have and account',
    goToLogIn: 'I already have an account',
    register: 'Register',
    name: 'Name',
    confirmPassword: 'Password Confirmation',
    city: 'City',
    invalidEmail: 'Invalid e-mail',
    wrongPassword: 'Invalid password',
    userNotFound: 'User not found. Do you want to create it?',
    disabledUser: 'Blocked user\nPlease contact contact@trailspot.app',
    emailAlreadyInUse: 'E-mail already in use. Did you forgot your password?',
    authError: 'Auth error. Please try again later',
  },
  'pt-BR': {
    email: 'E-mail',
    password: 'Senha',
    login: 'Entrar',
    facebookLogin: 'Entrar com Facebook',
    goToSignIn: 'Eu não tenho uma conta',
    goToLogIn: 'Eu já tenho uma conta',
    register: 'Criar conta',
    name: 'Nome',
    confirmPassword: 'Confirme sua senha',
    city: 'Cidade',
    invalidEmail: 'E-mail inválido',
    wrongPassword: 'Senha incorreta',
    userNotFound: 'Usuário inexistente. Quer criar uma conta?',
    disabledUser: 'Usuário bloqueado.\nEnvie um e-mail para contact@trailspot.app',
    emailAlreadyInUse: 'E-mail já cadastrado em outra conta. Você esqueceu sua senha?',
    authError: 'Erro de autenticação. Tente novamente mais tarde',
  },
};
